export type CsvDelimiter = ',' | ';';
export type ImportType = 'income' | 'expense';
export type DuplicateState = 'new' | 'likely_duplicate' | 'possible_duplicate' | 'invalid';
export type DateFormat = 'YYYY-MM-DD' | 'DD/MM/YYYY' | 'DD-MM-YYYY' | 'DD MMM YYYY';
export interface CsvTable { headers: string[]; rows: string[][]; delimiter: CsvDelimiter; }
export interface ImportMapping { date: string; time?: string; description?: string; amount?: string; debit?: string; credit?: string; reference?: string; currency?: string; dateFormat: DateFormat; signedAmount: 'positive_income' | 'positive_expense'; }
export interface ImportCategory { id: string; name: string; type: ImportType; }
export interface NormalizedImportRow { sourceRowNumber: number; occurredAt: string | null; description: string; amount: string | null; type: ImportType | null; currency: string; externalReference: string | null; suggestedCategoryId: string | null; categoryId: string | null; duplicateState: DuplicateState; validationMessage?: string; selectedForImport: boolean; sourceValue: string; }
export interface ExistingImportTransaction { occurredAt: string; amount: string | number; type: ImportType; description: string | null; reference: string | null; externalId: string | null; }

const aliases: Record<keyof Pick<ImportMapping, 'date' | 'description' | 'amount' | 'debit' | 'credit' | 'reference' | 'currency'>, string[]> = {
  date: ['date', 'tanggal', 'transaction date', 'datetime'], description: ['description', 'keterangan', 'merchant', 'memo', 'details', 'narration'], amount: ['amount', 'nominal', 'nilai'], debit: ['debit', 'keluar', 'withdrawal', 'dr'], credit: ['credit', 'masuk', 'deposit', 'cr'], reference: ['reference', 'ref', 'transaction id', 'nomor referensi'], currency: ['currency', 'mata uang', 'curr'],
};
export function detectDelimiter(text: string): CsvDelimiter { const lines = text.replace(/^\uFEFF/, '').split(/\r?\n/).filter(Boolean).slice(0, 5); return lines.reduce((score, line) => score + (line.split(';').length > line.split(',').length ? 1 : 0), 0) > lines.length / 2 ? ';' : ','; }
export function parseCsv(text: string): CsvTable {
  const delimiter = detectDelimiter(text); const rows: string[][] = []; let row: string[] = []; let value = ''; let quoted = false;
  const input = text.replace(/^\uFEFF/, '');
  for (let i = 0; i < input.length; i += 1) { const c = input[i]; if (quoted) { if (c === '"' && input[i + 1] === '"') { value += '"'; i += 1; } else if (c === '"') quoted = false; else value += c; continue; } if (c === '"') quoted = true; else if (c === delimiter) { row.push(value.trim()); value = ''; } else if (c === '\n') { row.push(value.trim()); if (row.some(Boolean)) rows.push(row); row = []; value = ''; } else if (c !== '\r') value += c; }
  if (quoted) throw new Error('The CSV contains an unclosed quoted value.'); if (value || row.length) { row.push(value.trim()); rows.push(row); } if (!rows.length) throw new Error('The CSV has no rows.');
  const headers = rows.shift()!.map((header, index) => header || `Column ${index + 1}`); return { headers, rows, delimiter };
}
export function autoMapping(headers: string[]): Partial<ImportMapping> { const find = (names: string[]) => headers.find((header) => names.includes(header.trim().toLowerCase())); return Object.fromEntries(Object.entries(aliases).map(([key, names]) => [key, find(names)]).filter(([, value]) => value)) as Partial<ImportMapping>; }
function value(row: string[], headers: string[], header?: string) { return header ? row[headers.indexOf(header)]?.trim() ?? '' : ''; }
export function normalizeMoney(raw: string): string | null {
  let input = raw.trim().replace(/^rp\s*/i, '').replace(/\s+(dr|cr)$/i, '').replace(/\s/g, ''); if (!input) return null; const negative = /^-/.test(input); input = input.replace(/^[+-]/, '');
  const comma = input.lastIndexOf(','); const dot = input.lastIndexOf('.'); let normalized = input;
  if (comma >= 0 && dot >= 0) normalized = comma > dot ? input.replace(/\./g, '').replace(',', '.') : input.replace(/,/g, '');
  else if (comma >= 0) normalized = input.slice(comma + 1).length <= 4 ? input.replace(',', '.') : input.replace(/,/g, '');
  else if (dot >= 0) normalized = input.slice(dot + 1).length === 3 ? input.replace(/\./g, '') : input.slice(dot + 1).length <= 4 ? input : input.replace(/\./g, '');
  if (!/^\d+(\.\d{1,4})?$/.test(normalized)) return null; return `${negative ? '-' : ''}${normalized}`;
}
export function normalizeDate(raw: string, format: DateFormat, time = ''): string | null { const text = raw.trim(); let year = ''; let month = ''; let day = ''; if (format === 'YYYY-MM-DD') [year, month, day] = text.split('-'); else if (format === 'DD/MM/YYYY') [day, month, year] = text.split('/'); else if (format === 'DD-MM-YYYY') [day, month, year] = text.split('-'); else { const match = text.match(/^(\d{1,2})\s+([A-Za-z]{3})\s+(\d{4})$/); if (!match) return null; day = match[1]; month = String(['jan','feb','mar','apr','may','jun','jul','aug','sep','oct','nov','dec'].indexOf(match[2].toLowerCase()) + 1); year = match[3]; } if (!/^\d{4}$/.test(year) || !/^\d{1,2}$/.test(month) || !/^\d{1,2}$/.test(day)) return null; const check = new Date(Date.UTC(Number(year), Number(month) - 1, Number(day))); if (check.getUTCFullYear() !== Number(year) || check.getUTCMonth() !== Number(month) - 1 || check.getUTCDate() !== Number(day)) return null; const date = `${year}-${month.padStart(2, '0')}-${day.padStart(2, '0')}`; const localTime = /^\d{1,2}:\d{2}/.test(time) ? time.padStart(5, '0') : '12:00'; try { return zonedDateTimeToIso(date, `${localTime}:00`, browserTimeZone()); } catch { return null; } }
export function normalizeRows(table: CsvTable, mapping: ImportMapping, currency: string, categories: ImportCategory[]): NormalizedImportRow[] { return table.rows.map((source, index) => { const rawAmount = mapping.amount ? value(source, table.headers, mapping.amount) : ''; const debit = normalizeMoney(value(source, table.headers, mapping.debit)); const credit = normalizeMoney(value(source, table.headers, mapping.credit)); const parsed = normalizeMoney(rawAmount); const marker = /\sDR$/i.test(rawAmount) ? 'expense' : /\sCR$/i.test(rawAmount) ? 'income' : null; const amountValue = parsed ?? credit ?? debit; const type: ImportType | null = parsed ? ((parsed.startsWith('-') ? mapping.signedAmount === 'positive_income' ? 'expense' : 'income' : marker ?? mapping.signedAmount === 'positive_income' ? 'income' : 'expense')) : credit ? 'income' : debit ? 'expense' : null; const amount = amountValue ? amountValue.replace('-', '') : null; const description = value(source, table.headers, mapping.description) || value(source, table.headers, mapping.reference); const occurredAt = normalizeDate(value(source, table.headers, mapping.date), mapping.dateFormat, value(source, table.headers, mapping.time)); const rowCurrency = value(source, table.headers, mapping.currency) || currency; const category = type ? categories.find((item) => item.type === type && description.toLowerCase().includes(item.name.toLowerCase())) : undefined; const validationMessage = !occurredAt ? 'Invalid or ambiguous date.' : !amount || !type ? 'Invalid amount or direction.' : !description ? 'Description or reference is required.' : rowCurrency !== currency ? 'Currency does not match the selected wallet.' : undefined; return { sourceRowNumber: index + 2, occurredAt, description, amount, type, currency: rowCurrency, externalReference: value(source, table.headers, mapping.reference) || null, suggestedCategoryId: category?.id ?? null, categoryId: category?.id ?? null, duplicateState: validationMessage ? 'invalid' : 'new', validationMessage, selectedForImport: !validationMessage, sourceValue: source.join(' | ') }; }); }
const descriptionKey = (value: string | null) => (value ?? '').toLowerCase().replace(/[^a-z0-9]+/g, ' ').trim();
export function classifyDuplicates(rows: NormalizedImportRow[], existing: ExistingImportTransaction[], timeZone = browserTimeZone()): NormalizedImportRow[] { const exactRefs = new Set(existing.filter((item) => item.reference || item.externalId).map((item) => `${item.reference ?? item.externalId}`.toLowerCase())); return rows.map((row): NormalizedImportRow => { if (row.duplicateState === 'invalid' || !row.amount || !row.type || !row.occurredAt) return row; const date = getLocalDateKey(row.occurredAt, timeZone); const same = existing.filter((item) => getLocalDateKey(item.occurredAt, timeZone) === date && Number(item.amount) === Number(row.amount) && item.type === row.type); const exact = row.externalReference && exactRefs.has(row.externalReference.toLowerCase()); const likely = same.some((item) => descriptionKey(item.description) === descriptionKey(row.description) && (!row.externalReference || !item.reference || item.reference.toLowerCase() === row.externalReference.toLowerCase())); const possible = same.length > 0; return { ...row, duplicateState: exact || likely ? 'likely_duplicate' : possible ? 'possible_duplicate' : 'new', selectedForImport: !(exact || likely) }; }); }
import { browserTimeZone, getLocalDateKey, zonedDateTimeToIso } from './date-time';
