import { supabase } from './supabase';
import type { NormalizedImportRow, ExistingImportTransaction } from './bank-statement-import';
import { assertOnline, offlineErrorMessage } from './connectivity';

async function userId() { const { data, error } = await supabase.auth.getUser(); if (error || !data.user) throw new Error('You must be signed in to import a statement.'); return data.user.id; }
export async function loadImportComparisonRows(walletId: string): Promise<ExistingImportTransaction[]> { const id = await userId(); const { data, error } = await supabase.from('transactions').select('occurred_at,amount,type,description,reference,external_id').eq('user_id', id).eq('wallet_id', walletId).is('deleted_at', null).in('type', ['income', 'expense']).limit(10000); if (error) throw error; return data.map((row) => ({ occurredAt: row.occurred_at, amount: row.amount, type: row.type as 'income' | 'expense', description: row.description, reference: row.reference, externalId: row.external_id })); }
async function fingerprint(walletId: string, row: NormalizedImportRow) { const source = `${walletId}|${row.externalReference?.toLowerCase() || ''}|${row.occurredAt}|${row.type}|${row.amount}|${row.description.toLowerCase().replace(/\s+/g, ' ').trim()}`; const digest = await crypto.subtle.digest('SHA-256', new TextEncoder().encode(source)); return Array.from(new Uint8Array(digest), (byte) => byte.toString(16).padStart(2, '0')).join(''); }
export async function commitBankStatementImport(input: { walletId: string; fileName: string; provider?: string; totalRows: number; duplicateRows: number; rejectedRows: number; rows: NormalizedImportRow[] }) { assertOnline(); const approved = input.rows.filter((row) => row.selectedForImport && row.duplicateState !== 'invalid' && row.amount && row.type && row.occurredAt && row.categoryId); const payload = await Promise.all(approved.map(async (row) => ({ occurred_at: row.occurredAt, description: row.description, amount: row.amount, type: row.type, currency: row.currency, reference: row.externalReference, category_id: row.categoryId, fingerprint: await fingerprint(input.walletId, row) }))); const { data, error } = await (supabase as any).rpc('import_bank_statement', { p_wallet_id: input.walletId, p_file_name: input.fileName, p_provider: input.provider ?? null, p_total_rows: input.totalRows, p_duplicate_rows: input.duplicateRows, p_rejected_rows: input.rejectedRows, p_rows: payload }); if (error) throw error; return data as { session_id: string; imported_rows: number; duplicate_rows: number; rejected_rows: number }; }
export function importErrorMessage(error: unknown) { const offline = offlineErrorMessage(error); if (offline) return offline; const code = error && typeof error === 'object' && 'code' in error ? String((error as { code: string }).code) : ''; if (code === '23505') return 'One or more approved rows were already imported. Refresh the review and try again.'; if (code === '42501') return 'Choose an active wallet you own.'; if (error instanceof Error && error.message.includes('signed in')) return error.message; return 'The statement could not be imported. No transactions were added.'; }
