import { useState } from 'react';
import type { Budget, BudgetPeriod } from '../../types/finance';
import { budgetCategoryOptions } from '../../data/budgets';
import { Button } from '../ui/Button';
import { Input } from '../ui/Input';
import { Modal } from '../ui/Modal';
import { Select } from '../ui/Select';

export interface BudgetFormValues { categoryId: string; monthlyLimit: string; period: BudgetPeriod; notes: string; }
const initialValues = (budget?: Budget | null): BudgetFormValues => ({ categoryId: budget?.categoryId ?? '', monthlyLimit: budget ? String(budget.monthlyLimit) : '', period: budget?.period ?? 'this-month', notes: budget?.notes ?? '' });
export function BudgetFormModal({ budget, duplicateError, onClose, onSubmit }: { budget?: Budget | null; duplicateError?: string; onClose: () => void; onSubmit: (values: BudgetFormValues) => void }) {
  const [values, setValues] = useState(() => initialValues(budget));
  const [errors, setErrors] = useState<Partial<Record<keyof BudgetFormValues, string>>>({});
  const update = <K extends keyof BudgetFormValues>(key: K, value: BudgetFormValues[K]) => { setValues(current => ({ ...current, [key]: value })); setErrors(current => ({ ...current, [key]: undefined })); };
  const save = () => { const next: typeof errors = {}; if (!values.categoryId) next.categoryId = 'Choose a category.'; if (!values.monthlyLimit || Number(values.monthlyLimit) <= 0) next.monthlyLimit = 'Enter a monthly limit greater than 0.'; if (!values.period) next.period = 'Choose a budget period.'; setErrors(next); if (!Object.keys(next).length) onSubmit(values); };
  return <Modal isOpen onClose={onClose} title={budget ? 'Edit Budget' : 'Create Budget'} description={budget ? 'Update the limit for this local category budget.' : 'Set a local monthly spending limit for a category.'} maxWidth="md" footer={<><Button variant="outline" size="sm" onClick={onClose}>Cancel</Button><Button variant="accent" size="sm" onClick={save}>{budget ? 'Save Changes' : 'Create Budget'}</Button></>}><form onSubmit={event=>{event.preventDefault();save();}} className="space-y-4"><div><label htmlFor="budget-category" className="block text-xs font-semibold text-primary mb-1.5">Category</label><Select id="budget-category" value={values.categoryId} disabled={Boolean(budget)} onChange={event=>update('categoryId', event.target.value)} options={[{value:'',label:'Choose a category'}, ...budgetCategoryOptions.map(category=>({value:category.id,label:category.name}))]} className="w-full h-10 rounded-[12px] bg-white" aria-invalid={Boolean(errors.categoryId)}/>{errors.categoryId&&<p className="mt-1 text-xs text-danger">{errors.categoryId}</p>}{duplicateError&&<p role="alert" className="mt-1 text-xs text-danger">{duplicateError}</p>}</div><div><label htmlFor="budget-limit" className="block text-xs font-semibold text-primary mb-1.5">Monthly Budget Limit</label><Input id="budget-limit" type="number" min="0.01" step="0.01" inputMode="decimal" value={values.monthlyLimit} onChange={event=>update('monthlyLimit',event.target.value)} placeholder="0.00" error={errors.monthlyLimit}/></div><div><label htmlFor="budget-period" className="block text-xs font-semibold text-primary mb-1.5">Period</label><Select id="budget-period" value={values.period} onChange={event=>update('period', event.target.value as BudgetPeriod)} options={[{value:'this-month',label:'This Month'}]} className="w-full h-10 rounded-[12px] bg-white" aria-invalid={Boolean(errors.period)}/>{errors.period&&<p className="mt-1 text-xs text-danger">{errors.period}</p>}</div><div><label htmlFor="budget-notes" className="block text-xs font-semibold text-primary mb-1.5">Notes <span className="font-normal text-secondary">(optional)</span></label><textarea id="budget-notes" rows={3} value={values.notes} onChange={event=>update('notes',event.target.value)} placeholder="Add a note for this local budget" className="w-full rounded-[12px] border border-border bg-white px-3.5 py-2.5 text-sm text-primary placeholder:text-secondary/70 focus:outline-none focus:border-primary focus:ring-1 focus:ring-primary resize-y"/></div></form></Modal>;
}
