import { useState } from 'react';
import type { Wallet, WalletCurrencyCode, WalletStatus, WalletType } from '../../types/finance';
import { walletCurrencyOptions } from '../../data/wallets';
import { Button } from '../ui/Button';
import { Input } from '../ui/Input';
import { Modal } from '../ui/Modal';
import { Select } from '../ui/Select';

export interface WalletFormValues { name: string; type: WalletType; currency: WalletCurrencyCode; openingBalance: string; monthlyLimit: string; accountMask: string; status: WalletStatus; }
const walletTypes: { value: WalletType; label: string }[] = [{value:'bank',label:'Bank Account'},{value:'cash',label:'Cash'},{value:'card',label:'Card'},{value:'savings',label:'Savings'},{value:'travel',label:'Travel'}];
const initial = (wallet?: Wallet | null): WalletFormValues => ({ name: wallet?.name ?? '', type: wallet?.type ?? 'bank', currency: wallet?.currency ?? 'USD', openingBalance: wallet ? String(wallet.balance) : '', monthlyLimit: wallet?.monthlyLimit === null ? '' : String(wallet?.monthlyLimit ?? ''), accountMask: wallet?.accountMask ?? '', status: wallet?.status ?? 'Active' });

export function WalletFormModal({ wallet, onClose, onSubmit }: { wallet?: Wallet | null; onClose: () => void; onSubmit: (values: WalletFormValues) => void }) {
  const [values, setValues] = useState(() => initial(wallet));
  const [errors, setErrors] = useState<Partial<Record<keyof WalletFormValues,string>>>({});
  const update = <K extends keyof WalletFormValues>(key: K, value: WalletFormValues[K]) => { setValues(v => ({...v,[key]:value})); setErrors(e => ({...e,[key]:undefined})); };
  const save = () => { const next: typeof errors = {}; if (!values.name.trim()) next.name='Wallet name is required.'; if (!values.type) next.type='Choose a wallet type.'; if (!values.currency) next.currency='Choose a currency.'; if (values.openingBalance && (!Number.isFinite(Number(values.openingBalance)) || Number(values.openingBalance) < 0)) next.openingBalance='Opening balance cannot be negative.'; if (values.monthlyLimit !== '' && (!Number.isFinite(Number(values.monthlyLimit)) || Number(values.monthlyLimit) < 0)) next.monthlyLimit='Monthly limit must be 0 or more.'; setErrors(next); if (!Object.keys(next).length) onSubmit(values); };
  return <Modal isOpen onClose={onClose} title={wallet ? 'Edit Wallet' : 'Add Wallet'} description={wallet ? 'Update persisted wallet details. Current balance is derived from its ledger.' : 'Add a persisted account or payment source. Opening balance is the starting ledger position.'} maxWidth="lg" footer={<><Button variant="outline" size="sm" onClick={onClose}>Cancel</Button><Button variant="accent" size="sm" onClick={save}>{wallet ? 'Save Changes' : 'Add Wallet'}</Button></>}>
    <form onSubmit={e=>{e.preventDefault();save();}} className="space-y-4">
      <div><label htmlFor="wallet-name" className="block text-xs font-semibold text-primary mb-1.5">Wallet Name</label><Input id="wallet-name" value={values.name} onChange={e=>update('name',e.target.value)} placeholder="e.g. USD Main Account" error={errors.name}/></div>
      <div className="grid grid-cols-1 sm:grid-cols-2 gap-4"><div><label htmlFor="wallet-type" className="block text-xs font-semibold text-primary mb-1.5">Wallet Type</label><Select id="wallet-type" value={values.type} onChange={e=>update('type',e.target.value as WalletType)} options={walletTypes} className="w-full h-10 rounded-[12px] bg-white" aria-invalid={Boolean(errors.type)}/>{errors.type&&<p className="mt-1 text-xs text-danger">{errors.type}</p>}</div><div><label htmlFor="wallet-currency" className="block text-xs font-semibold text-primary mb-1.5">Currency</label><Select id="wallet-currency" value={values.currency} onChange={e=>update('currency',e.target.value as WalletCurrencyCode)} options={walletCurrencyOptions.map(({value,label})=>({value,label}))} className="w-full h-10 rounded-[12px] bg-white" aria-invalid={Boolean(errors.currency)}/>{errors.currency&&<p className="mt-1 text-xs text-danger">{errors.currency}</p>}</div></div>
      {!wallet&&<div><label htmlFor="wallet-opening-balance" className="block text-xs font-semibold text-primary mb-1.5">Opening Balance</label><Input id="wallet-opening-balance" type="number" min="0" step="0.01" inputMode="decimal" value={values.openingBalance} onChange={e=>update('openingBalance',e.target.value)} placeholder="0.00" error={errors.openingBalance}/></div>}
      <div className="grid grid-cols-1 sm:grid-cols-2 gap-4"><div><label htmlFor="wallet-limit" className="block text-xs font-semibold text-primary mb-1.5">Monthly Limit <span className="font-normal text-secondary">(optional)</span></label><Input id="wallet-limit" type="number" min="0" step="0.01" inputMode="decimal" value={values.monthlyLimit} onChange={e=>update('monthlyLimit',e.target.value)} placeholder="No limit" error={errors.monthlyLimit}/></div><div><label htmlFor="wallet-label" className="block text-xs font-semibold text-primary mb-1.5">Account / Card Label <span className="font-normal text-secondary">(optional)</span></label><Input id="wallet-label" value={values.accountMask} onChange={e=>update('accountMask',e.target.value)} placeholder="e.g. •••• 2481"/></div></div>
      <div><label htmlFor="wallet-status" className="block text-xs font-semibold text-primary mb-1.5">Status</label><Select id="wallet-status" value={values.status} onChange={e=>update('status',e.target.value as WalletStatus)} options={[{value:'Active',label:'Active'},{value:'Inactive',label:'Inactive'}]} className="w-full h-10 rounded-[12px] bg-white"/></div>
    </form>
  </Modal>;
}
