import { useMemo, useState, type ChangeEvent } from 'react';
import { Modal } from '../ui/Modal';
import { Button } from '../ui/Button';
import { Select } from '../ui/Select';
import { Input } from '../ui/Input';
import { autoMapping, classifyDuplicates, normalizeRows, parseCsv, type CsvTable, type ImportMapping, type NormalizedImportRow } from '../../lib/bank-statement-import';
import { getLocalDateKey } from '../../lib/date-time';
import { loadImportComparisonRows, commitBankStatementImport, importErrorMessage } from '../../lib/bank-statement-import-service';

type Wallet = { id: string; name: string; currency: string; status?: string };
type Category = { id: string; name: string; type: 'income' | 'expense' };
const blankMapping: ImportMapping = { date: '', description: '', amount: '', debit: '', credit: '', reference: '', currency: '', dateFormat: 'YYYY-MM-DD', signedAmount: 'positive_income' };
export function BankStatementImportModal({ isOpen, onClose, wallets, categories, onImported }: { isOpen: boolean; onClose: () => void; wallets: Wallet[]; categories: Category[]; onImported: () => Promise<void> }) {
  const [file, setFile] = useState<File | null>(null); const [table, setTable] = useState<CsvTable | null>(null); const [walletId, setWalletId] = useState(wallets.find((wallet) => wallet.status !== 'Inactive')?.id ?? ''); const [mapping, setMapping] = useState<ImportMapping>(blankMapping); const [rows, setRows] = useState<NormalizedImportRow[]>([]); const [stage, setStage] = useState<'select' | 'map' | 'review' | 'result'>('select'); const [error, setError] = useState(''); const [busy, setBusy] = useState(false); const [result, setResult] = useState<{ imported_rows: number; duplicate_rows: number; rejected_rows: number } | null>(null);
  const wallet = wallets.find((item) => item.id === walletId); const headers = table?.headers ?? []; const headerOptions = [{ value: '', label: 'Not mapped' }, ...headers.map((header) => ({ value: header, label: header }))];
  const chooseFile = async (event: ChangeEvent<HTMLInputElement>) => { const selected = event.target.files?.[0]; if (!selected) return; setError(''); if (selected.size > 8 * 1024 * 1024) { setError('Choose a CSV under 8 MB.'); return; } try { const parsed = parseCsv(await selected.text()); const detected = autoMapping(parsed.headers); setFile(selected); setTable(parsed); setMapping({ ...blankMapping, ...detected, dateFormat: /^\d{4}-\d{2}-\d{2}$/.test(parsed.rows[0]?.[parsed.headers.indexOf(detected.date ?? '')] ?? '') ? 'YYYY-MM-DD' : 'DD/MM/YYYY' }); setStage('map'); } catch { setError('We could not read this CSV. Check its encoding, delimiter, and quoted values.'); } };
  const prepare = async () => { if (!table || !wallet || !mapping.date || (!mapping.amount && !mapping.debit && !mapping.credit) || (!mapping.description && !mapping.reference)) { setError('Map date, an amount or debit/credit, and a description or reference. Choose an active wallet.'); return; } setBusy(true); setError(''); try { const existing = await loadImportComparisonRows(wallet.id); setRows(classifyDuplicates(normalizeRows(table, mapping, wallet.currency, categories), existing)); setStage('review'); } catch { setError('We could not check existing transactions. Try again.'); } finally { setBusy(false); } };
  const summary = useMemo(() => rows.reduce((all, row) => { all[row.duplicateState] += 1; if (row.selectedForImport && row.amount && row.type) all[row.type] += Number(row.amount); return all; }, { new: 0, likely_duplicate: 0, possible_duplicate: 0, invalid: 0, income: 0, expense: 0 }), [rows]);
  const commit = async () => { if (!wallet || !file) return; setBusy(true); setError(''); try { const response = await commitBankStatementImport({ walletId: wallet.id, fileName: file.name, totalRows: rows.length, duplicateRows: summary.likely_duplicate + summary.possible_duplicate, rejectedRows: summary.invalid, rows }); await onImported(); setResult(response); setStage('result'); } catch (reason) { setError(importErrorMessage(reason)); } finally { setBusy(false); } };
  const update = (index: number, change: Partial<NormalizedImportRow>) => setRows((current) => current.map((row, rowIndex) => rowIndex === index ? { ...row, ...change } : row));
  return <Modal isOpen={isOpen} onClose={onClose} title="Import bank statement" description="Review a locally parsed CSV before approved rows become canonical transactions." maxWidth="xl" footer={<><Button variant="outline" size="sm" onClick={onClose} disabled={busy}>{stage === 'result' ? 'Close' : 'Cancel'}</Button>{stage === 'map' && <Button variant="accent" size="sm" onClick={() => void prepare()} loading={busy}>Review rows</Button>}{stage === 'review' && <Button variant="accent" size="sm" onClick={() => void commit()} loading={busy}>Confirm import</Button>}</>}>
    <div className="space-y-4"><ol className="flex flex-wrap gap-2 text-xs" aria-label="Import workflow">{['Select CSV', 'Map columns', 'Review', 'Complete'].map((label, index) => <li key={label} className={`rounded-full px-2.5 py-1 ${index <= ['select','map','review','result'].indexOf(stage) ? 'bg-accent/15 text-accent font-semibold' : 'bg-surface text-secondary'}`}>{index + 1}. {label}</li>)}</ol>{error && <p role="alert" className="rounded-lg bg-danger/10 p-3 text-sm text-danger">{error}</p>}
    {stage === 'select' && <section className="space-y-3"><label htmlFor="bank-statement-file" className="block text-sm font-semibold text-primary">Statement CSV</label><Input id="bank-statement-file" type="file" accept=".csv,text/csv" onChange={(event) => void chooseFile(event)} aria-describedby="bank-statement-help"/><p id="bank-statement-help" className="text-xs text-secondary">CSV is parsed locally. We do not upload the original file. UTF-8, UTF-8 BOM, comma/semicolon delimiters, quotes, CRLF and LF are supported.</p><label className="block text-sm font-semibold text-primary">Destination wallet</label><Select value={walletId} onChange={(event) => setWalletId(event.target.value)} options={wallets.filter((item) => item.status !== 'Inactive').map((item) => ({ value: item.id, label: `${item.name} (${item.currency})` }))}/></section>}
    {stage === 'map' && table && <section className="space-y-3"><p className="text-sm text-secondary">Detected {table.rows.length} data rows with a {table.delimiter === ';' ? 'semicolon' : 'comma'} delimiter. Review mappings; auto-detection is never final.</p><div className="grid grid-cols-1 sm:grid-cols-2 gap-3">{(['date','description','amount','debit','credit','reference','currency'] as const).map((key) => <label key={key} className="text-xs font-semibold text-primary capitalize">{key}<Select value={mapping[key] ?? ''} onChange={(event) => setMapping({ ...mapping, [key]: event.target.value })} options={headerOptions} className="mt-1 w-full"/></label>)}<label className="text-xs font-semibold text-primary">Date format<Select value={mapping.dateFormat} onChange={(event) => setMapping({ ...mapping, dateFormat: event.target.value as ImportMapping['dateFormat'] })} options={['YYYY-MM-DD','DD/MM/YYYY','DD-MM-YYYY','DD MMM YYYY'].map((value) => ({ value, label: value }))} className="mt-1 w-full"/></label><label className="text-xs font-semibold text-primary">Signed amount meaning<Select value={mapping.signedAmount} onChange={(event) => setMapping({ ...mapping, signedAmount: event.target.value as ImportMapping['signedAmount'] })} options={[{value:'positive_income',label:'+ income / − expense'},{value:'positive_expense',label:'+ expense / − income'}]} className="mt-1 w-full"/></label></div><p className="text-xs text-secondary">Preview: {table.rows.slice(0, 2).map((row) => row.join(' · ')).join(' / ')}</p></section>}
    {stage === 'review' && <section className="space-y-3"><div className="grid grid-cols-2 sm:grid-cols-4 gap-2 text-xs"><div className="rounded-lg bg-surface p-2">Ready: {summary.new + summary.possible_duplicate}</div><div className="rounded-lg bg-warning/15 p-2">Likely duplicate: {summary.likely_duplicate}</div><div className="rounded-lg bg-surface p-2">Possible: {summary.possible_duplicate}</div><div className="rounded-lg bg-danger/10 p-2">Invalid: {summary.invalid}</div></div><p className="text-xs text-secondary">Selected financial effect: income {summary.income.toLocaleString()} · expenses {summary.expense.toLocaleString()} {wallet?.currency}. Likely duplicates are excluded by default; you may explicitly include one.</p><div className="max-h-[48vh] overflow-auto rounded-xl border border-border"><table className="min-w-[760px] w-full text-left text-xs"><thead className="bg-surface text-secondary"><tr><th className="p-2">Include</th><th>Date</th><th>Description</th><th>Type</th><th>Amount</th><th>Category</th><th>Status</th></tr></thead><tbody>{rows.map((row, index) => <tr key={row.sourceRowNumber} className="border-t border-border"><td className="p-2"><input aria-label={`Include row ${row.sourceRowNumber}`} type="checkbox" checked={row.selectedForImport} disabled={row.duplicateState === 'invalid'} onChange={(event) => update(index, { selectedForImport: event.target.checked })}/></td><td>{row.occurredAt ? getLocalDateKey(row.occurredAt) : '—'}</td><td className="max-w-48 truncate">{row.description || '—'}</td><td><Select aria-label={`Type row ${row.sourceRowNumber}`} value={row.type ?? ''} onChange={(event) => update(index, { type: event.target.value as 'income' | 'expense' })} options={[{value:'income',label:'Income'},{value:'expense',label:'Expense'}]} /></td><td>{row.amount ?? '—'} {row.currency}</td><td><Select aria-label={`Category row ${row.sourceRowNumber}`} value={row.categoryId ?? ''} onChange={(event) => update(index, { categoryId: event.target.value || null })} options={[{value:'',label:'Choose'}, ...categories.filter((category) => category.type === row.type).map((category) => ({value:category.id,label:category.name}))]}/></td><td>{row.validationMessage ?? row.duplicateState.replace('_', ' ')}</td></tr>)}</tbody></table></div></section>}
    {stage === 'result' && result && <section className="rounded-xl bg-success/10 p-4"><h3 className="font-semibold text-primary">Reconciliation complete</h3><p className="mt-1 text-sm text-secondary">Imported {result.imported_rows} canonical transaction{result.imported_rows === 1 ? '' : 's'}. Skipped/reviewed duplicates: {result.duplicate_rows}. Invalid rows: {result.rejected_rows}.</p><p className="mt-2 text-xs text-secondary">Wallets, budgets, overview and reports have been revalidated. No raw statement file was stored.</p></section>}</div>
  </Modal>;
}
