import { Card } from '../ui/Card';
import type { OverviewMetric } from '../../lib/overview';
import { formatWalletAmount } from '../../lib/overview';
import type { WalletCurrencyCode } from '../../types/finance';
import { cn } from '../../lib/utils';

const icons: Record<OverviewMetric['id'], string> = { income: 'bi-arrow-down-left', expenses: 'bi-arrow-up-right', 'net-cash-flow': 'bi-activity', 'savings-rate': 'bi-percent' };
export interface MetricCardProps { metric: OverviewMetric; currency: WalletCurrencyCode; className?: string; }
export function MetricCard({ metric, currency, className }: MetricCardProps) { const highlighted = metric.id === 'income'; const formatted = metric.format === 'percentage' ? `${metric.amount.toFixed(1)}%` : formatWalletAmount(metric.amount, currency); return <Card className={cn('flex flex-col justify-between p-4 transition-all duration-200 sm:p-5', highlighted ? 'border-transparent bg-accent text-white shadow-[0_10px_25px_-5px_rgba(255,90,54,0.3)]' : 'border-border bg-white text-primary', className)}><div className="mb-3 flex items-center justify-between"><span className={cn('text-xs font-medium sm:text-sm', highlighted ? 'text-white/90' : 'text-secondary')}>{metric.title}</span><span className={cn('flex h-7 w-7 items-center justify-center rounded-full', highlighted ? 'bg-white/20 text-white' : 'bg-surface text-secondary')}><i className={`bi ${icons[metric.id]} text-sm`} aria-hidden="true" /></span></div><div className="my-1"><span className="font-sans text-2xl font-bold tracking-tight sm:text-[28px]">{formatted}</span></div><div className="mt-2 flex items-center gap-1.5"><span className={cn('inline-flex items-center gap-1 rounded-full px-1.5 py-0.5 text-[11px] font-semibold', highlighted ? 'bg-white/20 text-white' : metric.isPositive ? 'bg-success/15 text-success' : 'bg-danger/15 text-danger')}><i className={`bi ${metric.isPositive ? 'bi-arrow-up-right' : 'bi-arrow-down-right'}`} aria-hidden="true" /><span>{metric.isPositive ? 'Derived' : 'Outflow'}</span></span><span className={cn('text-[11px]', highlighted ? 'text-white/80' : 'text-secondary')}>{metric.trendLabel}</span></div></Card>; }
export default MetricCard;
