begin;
create type public.recurring_frequency as enum ('weekly','monthly');
create table public.recurring_transaction_rules (
 id uuid primary key default gen_random_uuid(), user_id uuid not null references public.profiles(id) on delete cascade, type public.category_type not null, wallet_id uuid not null, category_id uuid not null, amount numeric(20,4) not null, note text, frequency public.recurring_frequency not null, start_date date not null, end_date date, next_due_at timestamptz not null, local_time time not null, timezone text not null, active boolean not null default true, archived_at timestamptz, last_error text, created_at timestamptz not null default timezone('utc',now()), updated_at timestamptz not null default timezone('utc',now()),
 constraint recurring_wallet_owner foreign key(wallet_id,user_id) references public.wallets(id,user_id) on delete restrict, constraint recurring_category_owner foreign key(category_id,user_id) references public.categories(id,user_id) on delete restrict, constraint recurring_amount check(amount>0 and amount=round(amount,4)), constraint recurring_note check(note is null or char_length(trim(note))<=500), constraint recurring_dates check(end_date is null or end_date>=start_date)
);
create index recurring_rules_due_idx on public.recurring_transaction_rules(next_due_at) where active and archived_at is null;
alter table public.recurring_transaction_rules enable row level security;
create policy recurring_rules_owner on public.recurring_transaction_rules for all to authenticated using(user_id=(select auth.uid())) with check(user_id=(select auth.uid()));
create trigger recurring_rules_updated before update on public.recurring_transaction_rules for each row execute function public.set_updated_at();
create or replace function public.recurring_tz(p_user uuid) returns text language plpgsql stable security definer set search_path=public,pg_temp as $$ declare z text; begin select split_part(timezone,' ',1) into z from public.user_settings where user_id=p_user; if z is null or not exists(select 1 from pg_timezone_names where name=z) then return 'UTC'; end if; return z; end $$;
create or replace function public.recurring_due(d date,t time,z text) returns timestamptz language sql stable set search_path=public,pg_temp as $$select (d::timestamp+t) at time zone z$$;
create or replace function public.recurring_next(r public.recurring_transaction_rules) returns timestamptz language plpgsql stable set search_path=public,pg_temp as $$ declare d date:=(r.next_due_at at time zone r.timezone)::date; m date; day int; begin if r.frequency='weekly' then d:=d+7; else m:=(date_trunc('month',d)::date+interval '1 month')::date; day:=least(extract(day from r.start_date)::int,extract(day from (m+interval '1 month - 1 day'))::int); d:=m+day-1; end if; return public.recurring_due(d,r.local_time,r.timezone); end $$;
create or replace function public.validate_recurring_rule() returns trigger language plpgsql security definer set search_path=public,pg_temp as $$ declare w public.wallets%rowtype;c public.categories%rowtype;begin select * into w from public.wallets where id=new.wallet_id and user_id=new.user_id; select * into c from public.categories where id=new.category_id and user_id=new.user_id; if w.id is null or w.status<>'active' or w.deleted_at is not null then raise exception 'Choose an owned active wallet';end if;if c.id is null or c.status<>'active' or c.archived_at is not null or c.type<>new.type then raise exception 'Choose an owned active matching category';end if;new.timezone:=public.recurring_tz(new.user_id);return new;end $$;
create trigger recurring_rules_validate before insert or update on public.recurring_transaction_rules for each row execute function public.validate_recurring_rule();
create or replace function public.create_recurring_transaction_rule(p_type text,p_wallet_id uuid,p_category_id uuid,p_amount numeric,p_note text,p_frequency text,p_start_date date,p_end_date date default null,p_local_time time default '09:00') returns public.recurring_transaction_rules language plpgsql security definer set search_path=public,pg_temp as $$ declare u uuid:=auth.uid();r public.recurring_transaction_rules%rowtype;z text;begin if u is null then raise exception 'Authentication required';end if;if p_type not in('income','expense') or p_frequency not in('weekly','monthly') or p_amount is null or p_amount<=0 or p_amount<>round(p_amount,4) or(p_end_date is not null and p_end_date<p_start_date) then raise exception 'Invalid recurring rule';end if;z:=public.recurring_tz(u);insert into public.recurring_transaction_rules(user_id,type,wallet_id,category_id,amount,note,frequency,start_date,end_date,next_due_at,local_time,timezone) values(u,p_type::public.category_type,p_wallet_id,p_category_id,p_amount,nullif(trim(p_note),''),p_frequency::public.recurring_frequency,p_start_date,p_end_date,public.recurring_due(p_start_date,p_local_time,z),p_local_time,z)returning * into r;while r.next_due_at<=now() loop r.next_due_at:=public.recurring_next(r);end loop;update public.recurring_transaction_rules set next_due_at=r.next_due_at where id=r.id returning * into r;return r;end $$;
create or replace function public.set_recurring_transaction_rule_active(p_rule_id uuid,p_active boolean) returns void language plpgsql security definer set search_path=public,pg_temp as $$ declare r public.recurring_transaction_rules%rowtype;begin select * into r from public.recurring_transaction_rules where id=p_rule_id and user_id=auth.uid() and archived_at is null for update;if not found then raise exception 'Recurring rule not found';end if;if p_active then while r.next_due_at<=now() loop r.next_due_at:=public.recurring_next(r);end loop;end if;update public.recurring_transaction_rules set active=p_active,next_due_at=r.next_due_at,last_error=null where id=r.id;end $$;
create or replace function public.archive_recurring_transaction_rule(p_rule_id uuid) returns void language plpgsql security definer set search_path=public,pg_temp as $$ begin update public.recurring_transaction_rules set active=false,archived_at=now() where id=p_rule_id and user_id=auth.uid() and archived_at is null;end $$;
create or replace function public.process_recurring_transaction_rules(p_rule_limit int default 50,p_occurrences_per_rule int default 12) returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$ declare r public.recurring_transaction_rules%rowtype;w public.wallets%rowtype;c public.categories%rowtype;n int:=0;made int:=0;k int;key text;begin for r in select * from public.recurring_transaction_rules where active and archived_at is null and next_due_at<=now() order by next_due_at for update skip locked limit least(greatest(p_rule_limit,1),100) loop if not pg_try_advisory_xact_lock(hashtext('recurring:'||r.id::text)) then continue;end if;select * into w from public.wallets where id=r.wallet_id and user_id=r.user_id and status='active' and deleted_at is null;select * into c from public.categories where id=r.category_id and user_id=r.user_id and status='active' and archived_at is null and type=r.type;if w.id is null or c.id is null then update public.recurring_transaction_rules set active=false,last_error='Wallet or category is no longer active.' where id=r.id;continue;end if;k:=0;while r.next_due_at<=now() and(r.end_date is null or(r.next_due_at at time zone r.timezone)::date<=r.end_date)and k<least(greatest(p_occurrences_per_rule,1),12) loop key:='recurring:'||r.id::text||':'||to_char(r.next_due_at at time zone 'UTC','YYYYMMDD"T"HH24MISS"Z"');insert into public.transactions(user_id,wallet_id,category_id,type,amount,currency,description,note,occurred_at,status,source,idempotency_key,external_metadata) values(r.user_id,w.id,c.id,r.type,r.amount,w.currency,coalesce(nullif(r.note,''),'Recurring transaction'),nullif(r.note,''),r.next_due_at,'completed','recurring',key,jsonb_build_object('recurring_rule_id',r.id::text,'scheduled_occurrence',r.next_due_at)) on conflict(user_id,source,idempotency_key) where deleted_at is null do nothing;if found then made:=made+1;end if;r.next_due_at:=public.recurring_next(r);k:=k+1;end loop;if r.end_date is not null and(r.next_due_at at time zone r.timezone)::date>r.end_date then r.active:=false;end if;update public.recurring_transaction_rules set next_due_at=r.next_due_at,active=r.active where id=r.id;n:=n+1;end loop;return jsonb_build_object('processed_rules',n,'created_transactions',made,'catch_up_limit_per_rule',12);end $$;
create or replace function public.invoke_recurring_transaction_worker() returns void language plpgsql security definer set search_path=public,extensions as $$ declare u text;s text;begin select decrypted_secret into u from vault.decrypted_secrets where name='recurring_transaction_worker_url' limit 1;select decrypted_secret into s from vault.decrypted_secrets where name='recurring_transaction_worker_secret' limit 1;if u is not null and s is not null then perform net.http_post(url:=u,headers:=jsonb_build_object('content-type','application/json','x-worker-secret',s),body:='{}'::jsonb,timeout_milliseconds:=10000);end if;end $$;
do $$begin if not exists(select 1 from cron.job where jobname='recurring-transaction-worker') then perform cron.schedule('recurring-transaction-worker','* * * * *','select public.invoke_recurring_transaction_worker()');end if;end$$;
revoke all on function public.create_recurring_transaction_rule(text,uuid,uuid,numeric,text,text,date,date,time) from public;revoke all on function public.set_recurring_transaction_rule_active(uuid,boolean) from public;revoke all on function public.archive_recurring_transaction_rule(uuid) from public;revoke all on function public.process_recurring_transaction_rules(integer,integer) from public,anon,authenticated;revoke all on function public.invoke_recurring_transaction_worker() from public,anon,authenticated;grant execute on function public.create_recurring_transaction_rule(text,uuid,uuid,numeric,text,text,date,date,time) to authenticated;grant execute on function public.set_recurring_transaction_rule_active(uuid,boolean) to authenticated;grant execute on function public.archive_recurring_transaction_rule(uuid) to authenticated;grant execute on function public.process_recurring_transaction_rules(integer,integer) to service_role;
commit;
