begin;
create or replace function public.telegram_recurring_session(p_telegram_user_id text,p_telegram_chat_id text,p_action text,p_value text default null) returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$
declare i public.user_integrations%rowtype;s public.integration_sessions%rowtype;r public.recurring_transaction_rules%rowtype; refs jsonb; n text; rid uuid;begin
 if p_telegram_user_id !~ '^[0-9]+$' or p_telegram_chat_id !~ '^-?[0-9]+$' then return jsonb_build_object('status','unlinked');end if;
 select * into i from public.user_integrations where provider='telegram' and external_user_id=p_telegram_user_id and external_chat_id=p_telegram_chat_id and status='active' and deleted_at is null;if not found then return jsonb_build_object('status','unlinked');end if;
 if p_action='list' then select coalesce(jsonb_object_agg(rn,id),'{}'::jsonb) into refs from(select row_number() over(order by next_due_at)::text rn,id from public.recurring_transaction_rules where user_id=i.user_id and archived_at is null)q;update public.integration_sessions set status='canceled',deleted_at=now() where integration_id=i.id and flow='telegram_recurring' and status='active';insert into public.integration_sessions(user_id,integration_id,flow,step,payload,expires_at) values(i.user_id,i.id,'telegram_recurring','list',jsonb_build_object('rules',refs),now()+interval '30 minutes') returning * into s;return jsonb_build_object('status','linked','step','list','rules',coalesce((select jsonb_agg(jsonb_build_object('ref',q.rn,'type',q.type::text,'amount',q.amount,'currency',q.currency,'wallet',q.wallet,'category',q.category,'frequency',q.frequency::text,'next_due',q.next_due_at,'active',q.active)) from(select row_number()over(order by x.next_due_at)::text rn,x.type,x.amount,w.currency,w.name wallet,c.name category,x.frequency,x.next_due_at,x.active from public.recurring_transaction_rules x join public.wallets w on w.id=x.wallet_id join public.categories c on c.id=x.category_id where x.user_id=i.user_id and x.archived_at is null)q),'[]'::jsonb));end if;
 select * into s from public.integration_sessions where integration_id=i.id and flow='telegram_recurring' and status='active' and expires_at>now() for update;if not found then return jsonb_build_object('status','linked','step','none');end if;n=coalesce(p_value,'');rid=nullif(s.payload->'rules'->>n,'')::uuid;select * into r from public.recurring_transaction_rules where id=rid and user_id=i.user_id and archived_at is null for update;if not found then return jsonb_build_object('status','linked','step','list','error','Pilihan rutin tidak tersedia.');end if;
 if p_action='detail' then return jsonb_build_object('status','linked','step','detail','ref',n,'type',r.type::text,'amount',r.amount,'wallet',(select name from public.wallets where id=r.wallet_id),'currency',(select currency::text from public.wallets where id=r.wallet_id),'category',(select name from public.categories where id=r.category_id),'frequency',r.frequency::text,'next_due',r.next_due_at,'timezone',r.timezone,'active',r.active,'note',r.note);end if;
 if p_action='toggle' then update public.recurring_transaction_rules set active=not r.active where id=r.id;return public.telegram_recurring_session(p_telegram_user_id,p_telegram_chat_id,'detail',n);end if;
 if p_action='archive_request' then update public.integration_sessions set step='archive_confirm',payload=s.payload||jsonb_build_object('archive_ref',n) where id=s.id;return jsonb_build_object('status','linked','step','archive_confirm','ref',n);end if;
 if p_action='archive_confirm' then if s.step<>'archive_confirm' or s.payload->>'archive_ref'<>n then return jsonb_build_object('status','linked','step','none','error','Konfirmasi tidak aktif.');end if;update public.recurring_transaction_rules set active=false,archived_at=now() where id=r.id and user_id=i.user_id;update public.integration_sessions set status='completed' where id=s.id;return jsonb_build_object('status','linked','step','archived');end if;
 return jsonb_build_object('status','linked','step','none');end $$;
revoke all on function public.telegram_recurring_session(text,text,text,text) from public,anon,authenticated;grant execute on function public.telegram_recurring_session(text,text,text,text) to service_role;
commit;
