begin;
alter table public.telegram_budget_notification_events alter column budget_id drop not null;
alter table public.telegram_budget_notification_events drop constraint telegram_budget_notification_events_unique;
alter table public.telegram_budget_notification_events drop constraint telegram_budget_notification_events_threshold_check;
alter table public.telegram_budget_notification_events add constraint telegram_budget_notification_events_threshold_check check (threshold in ('budget_near_limit','budget_over_limit','daily_summary','weekly_summary'));
create unique index telegram_budget_notification_budget_period_unique on public.telegram_budget_notification_events (budget_id, period_start, threshold) where budget_id is not null;
create unique index telegram_finance_summary_period_unique on public.telegram_budget_notification_events (user_id, threshold, period_start) where threshold in ('daily_summary','weekly_summary');
create or replace function public.queue_telegram_finance_summaries() returns void language plpgsql security definer set search_path = public, pg_temp as $$
declare r record; z text; l timestamp; ps date; pe date; inc numeric; exp numeric; cnt integer; cats jsonb; buds jsonb;
begin
for r in select i.id integration_id,i.user_id,s.default_currency::text currency,s.timezone,p.preference_key from public.user_integrations i join public.user_settings s on s.user_id=i.user_id join public.notification_preferences p on p.user_id=i.user_id and p.channel='telegram' and p.enabled and p.preference_key in ('daily_summary','weekly_summary') where i.provider='telegram' and i.status='active' and i.deleted_at is null loop
 z:=split_part(coalesce(r.timezone,'UTC'),' ',1); if not exists(select 1 from pg_timezone_names where name=z) then z:='UTC'; end if; l:=now() at time zone z; if extract(hour from l)<>20 or (r.preference_key='weekly_summary' and extract(dow from l)<>0) then continue; end if;
 if r.preference_key='daily_summary' then ps:=l::date;pe:=ps+1; else ps:=l::date-extract(isodow from l)::integer+1;pe:=ps+7;end if;
 select coalesce(sum(amount) filter(where type='income'),0),coalesce(sum(amount) filter(where type='expense'),0),count(*) into inc,exp,cnt from public.transactions where user_id=r.user_id and currency::text=r.currency and status='completed' and transfer_id is null and deleted_at is null and occurred_at >= (ps::timestamp at time zone z) and occurred_at < (pe::timestamp at time zone z);
 select coalesce(jsonb_agg(jsonb_build_object('name',name,'amount',amount) order by amount desc),'[]'::jsonb) into cats from(select coalesce(c.name,'Tanpa kategori') name,sum(t.amount) amount from public.transactions t left join public.categories c on c.id=t.category_id where t.user_id=r.user_id and t.currency::text=r.currency and t.type='expense' and t.status='completed' and t.transfer_id is null and t.deleted_at is null and t.occurred_at >= (ps::timestamp at time zone z) and t.occurred_at < (pe::timestamp at time zone z) group by c.name order by amount desc limit 3)x;
 select coalesce(jsonb_agg(jsonb_build_object('category',category,'progress',progress) order by progress desc),'[]'::jsonb) into buds from(select coalesce(c.name,'Kategori') category,round(100*coalesce(sum(t.amount) filter(where t.type='expense' and t.status='completed' and t.transfer_id is null and t.deleted_at is null and t.currency=b.currency and t.occurred_at>=b.period_start and t.occurred_at<b.period_start+interval '1 month'),0)/b.limit_amount,1) progress from public.budgets b left join public.categories c on c.id=b.category_id left join public.transactions t on t.user_id=b.user_id and t.category_id=b.category_id where b.user_id=r.user_id and b.currency::text=r.currency and b.period_start=date_trunc('month',l)::date and b.archived_at is null group by c.name,b.limit_amount,b.currency,b.period_start)y where progress>=80 limit 3;
 insert into public.telegram_budget_notification_events(user_id,integration_id,budget_id,period_start,threshold,payload,next_retry_at) values(r.user_id,r.integration_id,null,ps,r.preference_key,jsonb_build_object('period_start',ps,'period_end',pe-1,'currency',r.currency,'income',inc,'expenses',exp,'net',inc-exp,'transaction_count',cnt,'categories',cats,'budgets',buds),now()) on conflict(user_id,threshold,period_start) where threshold in ('daily_summary','weekly_summary') do nothing;
end loop;end;$$;
revoke all on function public.queue_telegram_finance_summaries() from public,anon,authenticated; grant execute on function public.queue_telegram_finance_summaries() to service_role;
commit;